# infra/docker-compose.yml
services:
  postgres_db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
      POSTGRES_DB: devops
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend_app:
    build:
      context: ../BE
    container_name: backend_app
    environment:
      DB_HOST: postgres_db
      DB_USER: devops
      DB_PASSWORD: devops
      DB_NAME: devops
    ports:
      - "5001:5001"
    depends_on:
      - postgres_db
    networks:
      - app-network

  frontend:
    build:
      context: ../fe
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend_app
    networks:
      - app-network

volumes:
  pgdata:


networks:
  app-network:
    driver: bridge
