services:
  backend_app:
    build:
      context: ../BE
    container_name: backend_app
    environment:
      DB_HOST: devops-db.cjuuoys4a3cz.us-west-2.rds.amazonaws.com
      DB_USER: devops-db
      DB_PASS: devops-db
      DB_NAME: devops-db
      DB_PORT: 5432
    ports:
      - "5001:5001"
    networks:
      - app-network

  frontend:
    build:
      context: ../fe
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
