# backend/Dockerfile
FROM node:22-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy backend source code
COPY . .

# Expose port
EXPOSE 5001

# Start the server
CMD ["node", "server.js"]
